### ISSUE TITLE
please add GetMetaText method

### ISSUE THREAD

**Issue by laoqiuqiu** [tothpaul/PDFiumReader#12]
I want to get Metadata, but I can't find a related method.

**Comment by tothpaul** [comment]
what metadata are you seeking for ?

**Comment by laoqiuqiu** [comment]
"Title", "Author", "Subject", "Keywords", "Creator", "Producer", "CreationDate", or "ModDate"

**Comment by tothpaul** [comment]
add in version 1.0.2
