### ISSUE TITLE
How to convert a page into a picture?

### ISSUE THREAD

**Issue by laoqiuqiu** [tothpaul/PDFiumReader#13]

**Comment by tothpaul** [comment]
You can use IPDFPage.Render() to Bitmap.Canvas.Handle as a DC

**Comment by tothpaul** [comment]
there's now a new IPDFBitmap interface, it is used to reader forms, but you can use it to get a Bitmap of a page (see IPDFBitmap.GetInfo to access to the raw bitmap data)
