### ISSUE TITLE
The project is incomplete.

### ISSUE THREAD

**Issue by claudioprv** [tothpaul/PDFiumReader#17]
Hello friend, I really liked your project, but it is missing source code like SearchDlg, so it is impossible to compile it.
Do you intend to improve it?
I really liked the compiled example.
I would also like to port it to delphi 7, can you help me?

Thank you very much.
Claudio.

**Comment by tothpaul** [comment]
Hello, I've added the missing files

no, I'll dont take time to support Delphi 7, you have to: 
- remove dot in unit names
- extract inline types (TPDFPage) from it's parent class
- replace Helpers by raw procedure with the class as a parameter
- replace record methods by row procedure with the record as a parameter
- replace new components by older ones

you can also use Delphi Community Edition !
