### ISSUE TITLE
No viable commercial options?

### ISSUE THREAD

**Issue by edwinyzh** [tothpaul/PDFiumReader#18]
This component is great (see [https://en.delphipraxis.net/topic/5588-devexpress-pdf-viewer/?do=findComment&comment=48455](https://en.delphipraxis.net/topic/5588-devexpress-pdf-viewer/?do=findComment&comment=48455))

Unfortunately it's GPL-licensed so it's not usable in close-sourced commercial apps...

Would be great if you license it under MPL or provide buy links for an alternative commercial license, and add support for older version of Delphi (XE series).

**Comment by tothpaul** [comment]
A usage licence is now available on https://store.execute.fr

I no longer use the XE series, which version are you using, what is incompatible ?

I used an old version in XE3 so I guess it's not a big deal.

Regards

**Comment by edwinyzh** [comment]
That'll help people who want a commercial license and good for you ;)

IIRC, it's the TCard that's missing in old versions of Delphi.

**Comment by prtmon** [comment]
A bug was found, IPDFium. LoadFromFile ('Chinese file name ',' ')，err=3
