### ISSUE TITLE
A bug was found,chinese file name not loaded.

### ISSUE THREAD

**Issue by prtmon** [tothpaul/PDFiumReader#19]
A bug was found, IPDFium. LoadFromFile (pansichar('Chinese file name '),' ')，err=3

**Comment by tothpaul** [comment]
I think that it is a PDFIUM bug, it use CreateFileA() to open the file.
The last version of the code uses CreateFileW but I have some trouble to compile the last version :/
Anyway, you can use LoadFromMemory() with a TMemoryStream for instance.
Note that the stream have to be available until you close the document, PDFium do not keep a copy of it.

**Comment by tothpaul** [comment]
it's fixed in the release of today !

**Comment by prtmon** [comment]
Thank you for answering my question。
















At 2023-03-27 01:03:17, "Paul TOTH" ***@***.***> wrote:

I think that it is a PDFIUM bug, it use CreateFileA() to open the file.
The last version of the code uses CreateFileW but I have some trouble to compile the last version :/
Anyway, you can use LoadFromMemory() with a TMemoryStream for instance.
Note that the stream have to be available until you close the document, PDFium do not keep a copy of it.
