### ISSUE TITLE
Afficher la palette d'annotation?

### ISSUE THREAD

**Issue by bouhlal** [tothpaul/PDFiumReader#21]
Bonjour,
Je vous remercie pour les DLL.
Comment afficher la palette d'annotation?
Cordialement,

**Comment by tothpaul** [comment]
Il n'y a pas de palette d'annotation dans PDFiumReader

il est possible d'en ajouter une avec les fonctions IPDFPage.GetAnnotationCount(), IPDFPage.GetAnnotation() et IPDFAnnotation.GetString() avec les clés suivantes

  FPDFANNOT_TEXTTYPE_Contents = 'Contents';
  FPDFANNOT_TEXTTYPE_Author = 'T';
  FPDFANNOT_TEXTTYPE_Subject = 'Subj';
  FPDFANNOT_TEXTTYPE_Modified_Date = 'M';
  
  GetString s'utilise de la même façon que GetMetaText (voir TPDFiumFrame.GetProperty)

**Comment by bouhlal** [comment]
vous pouvez svp l'ajouter sur la demo?
Merci d'avance
