### ISSUE TITLE
Win10 touch screen computer touch slide pdf appears smear

### ISSUE THREAD

**Issue by yanniupai** [tothpaul/PDFiumReader#22]
Win10 touch screen computer touch slide pdf appears smear
![image](https://user-images.githubusercontent.com/29377917/228480884-38e3bf1b-5519-47df-8714-1148850aa98d.png)

**Comment by tothpaul** [comment]
I'm glad you like my application, but PDFiumReader is not intended to be a new PDF reader, it's a demonstration application for Delphi developers on the use of libPDFium in their developments.
However, contributions are welcome to enrich the demonstration.

**Comment by yanniupai** [comment]
I have written an OCX program based on this program, and it has been directly embedded in the ActiveX container for use, but there will be smearing, I don’t know if you can help me solve it

**Comment by tothpaul** [comment]
You know it's a GPL product ? if you want to use it in a commercial product you have to buy a licence on my store https://store.execute.fr/.

Now, I'm not sure of the solution, TPDFiumFrame uses already the DoubleBuffered option, so it should not smear.

PDFs are a large set of different documents, vectors are very slow to render, some have very large bitmaps, so the best way to render a specific PDF can vary wildly and it's hard to find a compromise that works in all case. Currently TPDFiumFrame.TPDFPage.Paint uses Bitmaps when there are Widgets and draws directly on the DC in other cases...you can try to always use Bitmaps but this may slow rendering in general.

**Comment by yanniupai** [comment]
Sorry, we decided to abandon your product and switch to SumatraPDF due to this smear bug, thank you
