### ISSUE TITLE
Copy selected text

### ISSUE THREAD

**Issue by e-delphi** [tothpaul/PDFiumReader#5]
`function TPDFiumFrame.GetSelectionText: String;`
`var`
`  Page: TPDFPage;`
`  awChar: Array[0..65535] of WideChar;`
`  wSelChar: PChar;`
`  Index: Integer;`
`begin`
`  wSelChar := @awChar;`
`  for Index := 0 to Pred(FPDF.GetPageCount) do`
`  begin`
`    Page := GetPage(Index);`
`    if (Page.SelStart = 0) and (Page.SelStop = 0) then`
`      Continue;`
`    Page.Text.GetText(Min(Page.SelStart, Page.SelStop), Max(Page.SelStart, Page.SelStop) - Min(Page.SelStart, Page.SelStop), wSelChar);`
`    Result := Result + WideCharToString(wSelChar);`
`  end;`
`end;`

**Comment by tothpaul** [comment]
code added
