### ISSUE TITLE
Can you help me to migrate this to lazarus

### ISSUE THREAD

**Issue by eldonfsr** [tothpaul/PDFiumReader#6]
I have project in lazarus and would like to read pdf files, can you help to migrate this.

thansk
Fernando Sandoval

**Comment by tothpaul** [comment]
Hi,

I don't use Lazarus, but I guess that Execute.libPDFium.pas should be Lazarus compatible..the Frame is just  wrapper for the IPDFium methods.

```
PDF_Create(PDFIUM_VERSION, FPDF);
FPDF.LoadFromFile(PAnsiChar(AnsiName), nil);
FPDF.GetPageSize(PageIndex, width, height); // if required
FPDF.GetPage(PageIndex, Page);
Page.Render(DC, Rect, Rotation, False);

```
For an hobby project, you can use the Delphi Community Edition :)

Regards
