### ISSUE TITLE
will it work on android?

### ISSUE THREAD

**Issue by jonahzheng** [tothpaul/PDFiumReader#8]
thank you
https://github.com/mshockwave/PdfiumAndroid/tree/master/src/main/jni/lib

**Comment by tothpaul** [comment]
I don't know, the first step is to compile PDFium for Android, I've never tried to do that.
then it should work as any native library, 
finally there's no HDC under Android, so the Render part have to be reviewed.

I don't have time to explore that yet.

Regards
