### ISSUE TITLE
would it be available for Lazarus (free pascal)?

### ISSUE THREAD

**Issue by alas82** [tothpaul/PDFiumReader#9]

**Comment by tothpaul** [comment]
I don't use Lazarus,

the DLL is usable under Lazarus, I guess that Execute.libPDFium is FPC compatible (does it supports dotted unit names now ?)

for the visual part, it uses Delphi VCL, I don't know how far Lazarus is compatible, but at least the code can probably be adapted with few efforts...that I will not provide :)

Regards
